set fileencodings=utf-8,gb2312,gb18030,gbk,ucs-bom,cp936,latin1
set nocompatible              " be iMproved, required
set nu!                                    "显示行号
syntax on                                "语法高亮度显示
" 开启文件类型侦测
filetype on
" 根据侦测到的不同类型加载对应的插件
filetype plugin on
let javascript_enable_domhtmlcss = 1
let g:javascript_plugin_jsdoc = 1
map <F2> :NERDTreeToggle<CR>

" 显示行号
let NERDTreeShowLineNumbers=1
let NERDTreeAutoCenter=1
" 是否显示隐藏文件
let NERDTreeShowHidden=1

" set the runtime path to include Vundle and initialize
set rtp+=~/.vim/bundle/Vundle.vim
call vundle#begin()

" let Vundle manage Vundle, required
Plugin 'VundleVim/Vundle.vim'
Plugin 'pangloss/vim-javascript'
Plugin 'scrooloose/nerdtree'
Plugin 'heavenshell/vim-jsdoc'

" 所有的插件需要在这一行之前添加
call vundle#end()            " required
filetype plugin indent on    " required
